Revert skybox classification tests
This reverts commit 38b7dfe6eb8cdfa6f44f2bf73d636265883793df.

Revert "Fix missing ID crash"

This reverts commit 89a45196446c610b3787cc78b20ee9e8891a950c.

Revert "Fix error C2371"

This reverts commit c37e1a732207fbc7dfe80953bcda1bfa422a651d.

Revert "Improve skybox detection"

This reverts commit adb63dd0362d3417f0fbcc873cb38095a3ae19f5.

Reapply "Force only sky candidates into stereo"

This reverts commit a2006d4e0d080151af0c9f83e576b11d39c3d994.

Revert "Force only sky candidates into stereo"

This reverts commit 6e81fb6c47ccb17f6ed2f1dcab532ff7ea88a3c2.

Reapply "Temporarily stereoize everything"

This reverts commit 53292c170614c2b9582947c5f707ca05e613bb3c.

Revert "Temporarily stereoize everything"

This reverts commit 247f2bfdb68be2d8d2442fe95920b8ecbec7edf5.