Revert sky detection test slop
This reverts commit eb691e1fddc4939be1eff611382a9022665b791b.

Revert "Fix warning C4029"

This reverts commit bd0c7413cd356c544e1ebe374ac18dd1805248ec.

Reapply "Fix warning C4029"

This reverts commit 5850c1941d7167cceb87714fd9989ee75a61a205.

Revert "Log shader analysis"

This reverts commit c5ada1d584ddbeae84249c0662dbd50618b04bac.

Revert "Include hash in STEREO_INJECTED logger"

This reverts commit d004697f5b26ac3cd87ab45bcdbc36529c915ddd.

Revert "Override sky depth to infinity"

This reverts commit 3c1cee601b9878a9364609788c996402198cdc9e.

Revert "define SpvOpCopyObject"

This reverts commit 97e3b1f0a0f98ef6b6e3dc72d9884b123fe474ae.

Revert "Improve sky detection"

This reverts commit bc0dd896de2d2ff541de909e6b579f6b8e702e04.

Revert "Fix sky depth override activation"

This reverts commit 94f3d70883aab3fef3a6ca913a97d34f9a3d82c0.

Revert "Fix ID collision"

This reverts commit ff1d7d620d5b4a031aa58bb37c0306a5476a5a3f.

Revert "Use safe + deterministic force_far_depth"

This reverts commit cee6eedf84fbc13d0f69bc835c5df5fe73942448.

Revert "Add missing comment"

This reverts commit 336463d3fc7b5ebb8815f66e8cf5104246b2f843.

Revert "Fix sky false positive flattening stereo"

This reverts commit 0c3d9c188232c8bc25a32af058b2316311b191eb.

Revert "Fix compilation error C2231"

This reverts commit da78db059038aedc038a265352db47cdb845108e.

Revert "Exclude sky from stereo bypass"

This reverts commit 38b7dfe6eb8cdfa6f44f2bf73d636265883793df.

Revert "Temporarily stereoize everything"

This reverts commit 247f2bfdb68be2d8d2442fe95920b8ecbec7edf5.

Reapply "Temporarily stereoize everything"

This reverts commit 53292c170614c2b9582947c5f707ca05e613bb3c.

Revert "Force only sky candidates into stereo"

This reverts commit 6e81fb6c47ccb17f6ed2f1dcab532ff7ea88a3c2.

Reapply "Force only sky candidates into stereo"

This reverts commit a2006d4e0d080151af0c9f83e576b11d39c3d994.

Revert "Improve skybox detection"

This reverts commit adb63dd0362d3417f0fbcc873cb38095a3ae19f5.

Revert "Fix error C2371"

This reverts commit c37e1a732207fbc7dfe80953bcda1bfa422a651d.

Revert "Fix missing ID crash"

This reverts commit 89a45196446c610b3787cc78b20ee9e8891a950c.

Revert "Revert skybox classification tests"

This reverts commit 3c5959648e2c07f730825aa70176463ab4e6d9fc.

Revert "Log skybox shader candidate"

This reverts commit 5d60b4eaf6395d8a2b4d9d859b1214a7be38c84e.

Revert "Fix skybox shader candidate logger"

This reverts commit 8af50244088c4d2fea952ada60d3833c6cbcdc4d.

Revert "Log skybox candidate shader attributes"

This reverts commit b06d1f5f8e37f966feeb444d9a0a772da4ed85b7.

Revert "Move skybox shader candidate logger"

This reverts commit 5f5824521ab4a8fb2a99bd21251edc1eb795fded.

Revert "Exclude skybox from UI stereo bypass"

This reverts commit 4a43139c41063e46e4c9fdaf4f28ec83de8b552a.

Revert "Tighten sky classification"

This reverts commit e696a2868df7b1d78a69f4b736bb93bd9bc534ff.

Revert "Don't classify sky as screenspace quad"

This reverts commit 18aa724086383bcc1f4dd8bfbd2ede770b103171.

Revert "Fix SpvOpStore detection"

This reverts commit 3aabe19e229b9bc271b222047c8f76200e6cc759.

Revert "Fix sky exclusion from screenspace logic"

This reverts commit c45c2a9800acb3a7dc9f15a134dd29132775ba85.

Revert "Force synthetic view offset for sky"

This reverts commit 845ee785fd7c1c637e85ac5bce713667257fb951.

Revert "Fix compilation, add logging and clean up"

This reverts commit 7093764d1e6767c80da282bd0583797d1890cdde.

Revert "Disable suspected sky shader and log stages"

This reverts commit 079b8a6c7bc4c1b4e44007b9a61d5c029ecb80dc.

Revert "Update shader.c"

This reverts commit cdf16c46827084f27bc7ccee6d3e8ba8f1a6f1e6.

Revert "Log fragment shaders"

This reverts commit 9a6084764a4ff73af8fbbe31e67eca4b17df4d34.